# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/GitHub/Mud-Py-Analyser/Forms/main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 532)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.summary = QtWidgets.QWidget()
        self.summary.setObjectName("summary")
        self.tabWidget.addTab(self.summary, "")
        self.zone = QtWidgets.QWidget()
        self.zone.setObjectName("zone")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.zone)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_Zone = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Zone.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_Zone.setObjectName("horizontalLayout_Zone")
        self.groupBoxZone = QtWidgets.QGroupBox(self.zone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxZone.sizePolicy().hasHeightForWidth())
        self.groupBoxZone.setSizePolicy(sizePolicy)
        self.groupBoxZone.setTitle("")
        self.groupBoxZone.setObjectName("groupBoxZone")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxZone)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayoutZone1 = QtWidgets.QVBoxLayout()
        self.verticalLayoutZone1.setObjectName("verticalLayoutZone1")
        self.groupBoxZone1 = QtWidgets.QGroupBox(self.groupBoxZone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxZone1.sizePolicy().hasHeightForWidth())
        self.groupBoxZone1.setSizePolicy(sizePolicy)
        self.groupBoxZone1.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxZone1.setTitle("")
        self.groupBoxZone1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxZone1.setCheckable(False)
        self.groupBoxZone1.setObjectName("groupBoxZone1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBoxZone1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.comboBoxZone = QtWidgets.QComboBox(self.groupBoxZone1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxZone.sizePolicy().hasHeightForWidth())
        self.comboBoxZone.setSizePolicy(sizePolicy)
        self.comboBoxZone.setObjectName("comboBoxZone")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxZone)
        self.labelValueType_3 = QtWidgets.QLabel(self.groupBoxZone1)
        self.labelValueType_3.setObjectName("labelValueType_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelValueType_3)
        self.comboBoxSensorTypeZone = QtWidgets.QComboBox(self.groupBoxZone1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSensorTypeZone.sizePolicy().hasHeightForWidth())
        self.comboBoxSensorTypeZone.setSizePolicy(sizePolicy)
        self.comboBoxSensorTypeZone.setObjectName("comboBoxSensorTypeZone")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxSensorTypeZone)
        self.labelZone = QtWidgets.QLabel(self.groupBoxZone1)
        self.labelZone.setObjectName("labelZone")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelZone)
        self.verticalLayoutZone1.addWidget(self.groupBoxZone1)
        self.timeRangeZone = TimeRangePicker(self.groupBoxZone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeRangeZone.sizePolicy().hasHeightForWidth())
        self.timeRangeZone.setSizePolicy(sizePolicy)
        self.timeRangeZone.setMinimumSize(QtCore.QSize(0, 20))
        self.timeRangeZone.setObjectName("timeRangeZone")
        self.verticalLayoutZone1.addWidget(self.timeRangeZone)
        self.progressBarZonePlot = QtWidgets.QProgressBar(self.groupBoxZone)
        self.progressBarZonePlot.setProperty("value", 0)
        self.progressBarZonePlot.setObjectName("progressBarZonePlot")
        self.verticalLayoutZone1.addWidget(self.progressBarZonePlot)
        self.pushButtonPlotZone = QtWidgets.QPushButton(self.groupBoxZone)
        self.pushButtonPlotZone.setObjectName("pushButtonPlotZone")
        self.verticalLayoutZone1.addWidget(self.pushButtonPlotZone)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutZone1.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBoxZone)
        self.label.setObjectName("label")
        self.verticalLayoutZone1.addWidget(self.label)
        self.doubleSpinBoxZonePlayHoursPerSecond = QtWidgets.QDoubleSpinBox(self.groupBoxZone)
        self.doubleSpinBoxZonePlayHoursPerSecond.setMinimum(0.5)
        self.doubleSpinBoxZonePlayHoursPerSecond.setMaximum(48.0)
        self.doubleSpinBoxZonePlayHoursPerSecond.setProperty("value", 6.0)
        self.doubleSpinBoxZonePlayHoursPerSecond.setObjectName("doubleSpinBoxZonePlayHoursPerSecond")
        self.verticalLayoutZone1.addWidget(self.doubleSpinBoxZonePlayHoursPerSecond)
        self.pushButtonZonePlay = QtWidgets.QPushButton(self.groupBoxZone)
        self.pushButtonZonePlay.setObjectName("pushButtonZonePlay")
        self.verticalLayoutZone1.addWidget(self.pushButtonZonePlay)
        self.verticalLayout_5.addLayout(self.verticalLayoutZone1)
        self.horizontalLayout_Zone.addWidget(self.groupBoxZone)
        self.groupBoxZonePlots = QtWidgets.QGroupBox(self.zone)
        self.groupBoxZonePlots.setTitle("")
        self.groupBoxZonePlots.setObjectName("groupBoxZonePlots")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxZonePlots)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxZonePlotHeader = QtWidgets.QGroupBox(self.groupBoxZonePlots)
        self.groupBoxZonePlotHeader.setTitle("")
        self.groupBoxZonePlotHeader.setObjectName("groupBoxZonePlotHeader")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxZonePlotHeader)
        self.gridLayout.setObjectName("gridLayout")
        self.labelZonePlotDateTime = QtWidgets.QLabel(self.groupBoxZonePlotHeader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelZonePlotDateTime.sizePolicy().hasHeightForWidth())
        self.labelZonePlotDateTime.setSizePolicy(sizePolicy)
        self.labelZonePlotDateTime.setText("")
        self.labelZonePlotDateTime.setObjectName("labelZonePlotDateTime")
        self.gridLayout.addWidget(self.labelZonePlotDateTime, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxZonePlotHeader)
        self.zonePlot = ImageView(self.groupBoxZonePlots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zonePlot.sizePolicy().hasHeightForWidth())
        self.zonePlot.setSizePolicy(sizePolicy)
        self.zonePlot.setObjectName("zonePlot")
        self.verticalLayout.addWidget(self.zonePlot)
        self.horizontalLayout_Zone.addWidget(self.groupBoxZonePlots)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_Zone)
        self.tabWidget.addTab(self.zone, "")
        self.sensor = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor.sizePolicy().hasHeightForWidth())
        self.sensor.setSizePolicy(sizePolicy)
        self.sensor.setObjectName("sensor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.sensor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_Sensor = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Sensor.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_Sensor.setObjectName("horizontalLayout_Sensor")
        self.groupBoxSensor_2 = QtWidgets.QGroupBox(self.sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSensor_2.sizePolicy().hasHeightForWidth())
        self.groupBoxSensor_2.setSizePolicy(sizePolicy)
        self.groupBoxSensor_2.setTitle("")
        self.groupBoxSensor_2.setObjectName("groupBoxSensor_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxSensor_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutSensor = QtWidgets.QVBoxLayout()
        self.verticalLayoutSensor.setObjectName("verticalLayoutSensor")
        self.groupBoxSensor = QtWidgets.QGroupBox(self.groupBoxSensor_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSensor.sizePolicy().hasHeightForWidth())
        self.groupBoxSensor.setSizePolicy(sizePolicy)
        self.groupBoxSensor.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxSensor.setTitle("")
        self.groupBoxSensor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxSensor.setCheckable(False)
        self.groupBoxSensor.setObjectName("groupBoxSensor")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxSensor)
        self.formLayout.setObjectName("formLayout")
        self.comboBoxSensorID = QtWidgets.QComboBox(self.groupBoxSensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSensorID.sizePolicy().hasHeightForWidth())
        self.comboBoxSensorID.setSizePolicy(sizePolicy)
        self.comboBoxSensorID.setObjectName("comboBoxSensorID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxSensorID)
        self.labelValueType = QtWidgets.QLabel(self.groupBoxSensor)
        self.labelValueType.setObjectName("labelValueType")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelValueType)
        self.comboBoxSensorType = QtWidgets.QComboBox(self.groupBoxSensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSensorType.sizePolicy().hasHeightForWidth())
        self.comboBoxSensorType.setSizePolicy(sizePolicy)
        self.comboBoxSensorType.setObjectName("comboBoxSensorType")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxSensorType)
        self.labelSensorID = QtWidgets.QLabel(self.groupBoxSensor)
        self.labelSensorID.setObjectName("labelSensorID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSensorID)
        self.verticalLayoutSensor.addWidget(self.groupBoxSensor)
        self.timeRange = TimeRangePicker(self.groupBoxSensor_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeRange.sizePolicy().hasHeightForWidth())
        self.timeRange.setSizePolicy(sizePolicy)
        self.timeRange.setMinimumSize(QtCore.QSize(0, 20))
        self.timeRange.setObjectName("timeRange")
        self.verticalLayoutSensor.addWidget(self.timeRange)
        self.pushButtonPlot = QtWidgets.QPushButton(self.groupBoxSensor_2)
        self.pushButtonPlot.setObjectName("pushButtonPlot")
        self.verticalLayoutSensor.addWidget(self.pushButtonPlot)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutSensor.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayoutSensor)
        self.horizontalLayout_Sensor.addWidget(self.groupBoxSensor_2)
        self.sensorPlot = PlotWidget(self.sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorPlot.sizePolicy().hasHeightForWidth())
        self.sensorPlot.setSizePolicy(sizePolicy)
        self.sensorPlot.setObjectName("sensorPlot")
        self.horizontalLayout_Sensor.addWidget(self.sensorPlot)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_Sensor)
        self.tabWidget.addTab(self.sensor, "")
        self.control_node = QtWidgets.QWidget()
        self.control_node.setObjectName("control_node")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.control_node)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_ControlNode = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ControlNode.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_ControlNode.setObjectName("horizontalLayout_ControlNode")
        self.groupBoxControlNode = QtWidgets.QGroupBox(self.control_node)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxControlNode.sizePolicy().hasHeightForWidth())
        self.groupBoxControlNode.setSizePolicy(sizePolicy)
        self.groupBoxControlNode.setTitle("")
        self.groupBoxControlNode.setObjectName("groupBoxControlNode")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxControlNode)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayoutControlNode = QtWidgets.QVBoxLayout()
        self.verticalLayoutControlNode.setObjectName("verticalLayoutControlNode")
        self.groupBoxControlNode1 = QtWidgets.QGroupBox(self.groupBoxControlNode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxControlNode1.sizePolicy().hasHeightForWidth())
        self.groupBoxControlNode1.setSizePolicy(sizePolicy)
        self.groupBoxControlNode1.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxControlNode1.setTitle("")
        self.groupBoxControlNode1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxControlNode1.setCheckable(False)
        self.groupBoxControlNode1.setObjectName("groupBoxControlNode1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBoxControlNode1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.comboBoxControlNodeID = QtWidgets.QComboBox(self.groupBoxControlNode1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxControlNodeID.sizePolicy().hasHeightForWidth())
        self.comboBoxControlNodeID.setSizePolicy(sizePolicy)
        self.comboBoxControlNodeID.setObjectName("comboBoxControlNodeID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxControlNodeID)
        self.labelValueType_2 = QtWidgets.QLabel(self.groupBoxControlNode1)
        self.labelValueType_2.setObjectName("labelValueType_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelValueType_2)
        self.comboBoxControlNodeType = QtWidgets.QComboBox(self.groupBoxControlNode1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxControlNodeType.sizePolicy().hasHeightForWidth())
        self.comboBoxControlNodeType.setSizePolicy(sizePolicy)
        self.comboBoxControlNodeType.setObjectName("comboBoxControlNodeType")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxControlNodeType)
        self.labelControlNodeID = QtWidgets.QLabel(self.groupBoxControlNode1)
        self.labelControlNodeID.setObjectName("labelControlNodeID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelControlNodeID)
        self.verticalLayoutControlNode.addWidget(self.groupBoxControlNode1)
        self.timeRangeControlNode = TimeRangePicker(self.groupBoxControlNode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeRangeControlNode.sizePolicy().hasHeightForWidth())
        self.timeRangeControlNode.setSizePolicy(sizePolicy)
        self.timeRangeControlNode.setMinimumSize(QtCore.QSize(0, 20))
        self.timeRangeControlNode.setObjectName("timeRangeControlNode")
        self.verticalLayoutControlNode.addWidget(self.timeRangeControlNode)
        self.pushButtonPlotControlNode = QtWidgets.QPushButton(self.groupBoxControlNode)
        self.pushButtonPlotControlNode.setObjectName("pushButtonPlotControlNode")
        self.verticalLayoutControlNode.addWidget(self.pushButtonPlotControlNode)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutControlNode.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.verticalLayoutControlNode)
        self.horizontalLayout_ControlNode.addWidget(self.groupBoxControlNode)
        self.controlNodePlot = PlotWidget(self.control_node)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlNodePlot.sizePolicy().hasHeightForWidth())
        self.controlNodePlot.setSizePolicy(sizePolicy)
        self.controlNodePlot.setObjectName("controlNodePlot")
        self.horizontalLayout_ControlNode.addWidget(self.controlNodePlot)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_ControlNode)
        self.tabWidget.addTab(self.control_node, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mud-Py Analyser"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.summary), _translate("MainWindow", "Summary"))
        self.labelValueType_3.setText(_translate("MainWindow", "Value Type"))
        self.labelZone.setText(_translate("MainWindow", "Zone"))
        self.pushButtonPlotZone.setText(_translate("MainWindow", "Plot"))
        self.label.setText(_translate("MainWindow", "Hours per Second (fps)"))
        self.pushButtonZonePlay.setText(_translate("MainWindow", "Play"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zone), _translate("MainWindow", "Zone"))
        self.labelValueType.setText(_translate("MainWindow", "Value Type"))
        self.labelSensorID.setText(_translate("MainWindow", "Sensor ID"))
        self.pushButtonPlot.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sensor), _translate("MainWindow", "Sensor"))
        self.labelValueType_2.setText(_translate("MainWindow", "Value Type"))
        self.labelControlNodeID.setText(_translate("MainWindow", "Control Node ID"))
        self.pushButtonPlotControlNode.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_node), _translate("MainWindow", "Control Node"))
from Forms.TimeRangePicker import TimeRangePicker
from pyqtgraph import ImageView, PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
