# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/GitHub/Mud-Py-Analyser/Forms/main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 818)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 701, 601))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.summary = QtWidgets.QWidget()
        self.summary.setObjectName("summary")
        self.tabWidget.addTab(self.summary, "")
        self.zone = QtWidgets.QWidget()
        self.zone.setObjectName("zone")
        self.tabWidget.addTab(self.zone, "")
        self.sensor = QtWidgets.QWidget()
        self.sensor.setObjectName("sensor")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.sensor)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 561))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBoxSensor = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSensor.sizePolicy().hasHeightForWidth())
        self.groupBoxSensor.setSizePolicy(sizePolicy)
        self.groupBoxSensor.setTitle("")
        self.groupBoxSensor.setObjectName("groupBoxSensor")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxSensor)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 241, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelSensorID = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensorID.setObjectName("labelSensorID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSensorID)
        self.comboBoxSensorID = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxSensorID.setObjectName("comboBoxSensorID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxSensorID)
        self.labelValueType = QtWidgets.QLabel(self.layoutWidget)
        self.labelValueType.setObjectName("labelValueType")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelValueType)
        self.comboBoxSensorType = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxSensorType.setObjectName("comboBoxSensorType")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxSensorType)
        self.labelStart = QtWidgets.QLabel(self.layoutWidget)
        self.labelStart.setObjectName("labelStart")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelStart)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.labelEnd = QtWidgets.QLabel(self.layoutWidget)
        self.labelEnd.setObjectName("labelEnd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelEnd)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit_2)
        self.labelStepSize = QtWidgets.QLabel(self.layoutWidget)
        self.labelStepSize.setObjectName("labelStepSize")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelStepSize)
        self.comboBoxStepSize = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxStepSize.setObjectName("comboBoxStepSize")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBoxStepSize)
        self.pushButtonPlot = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonPlot.setObjectName("pushButtonPlot")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButtonPlot)
        self.horizontalLayout.addWidget(self.groupBoxSensor)
        self.sensorPlot = PlotWidget(self.horizontalLayoutWidget)
        self.sensorPlot.setObjectName("sensorPlot")
        self.horizontalLayout.addWidget(self.sensorPlot)
        self.tabWidget.addTab(self.sensor, "")
        self.control_node = QtWidgets.QWidget()
        self.control_node.setObjectName("control_node")
        self.tabWidget.addTab(self.control_node, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.summary), _translate("MainWindow", "Summary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zone), _translate("MainWindow", "Zone"))
        self.labelSensorID.setText(_translate("MainWindow", "Sensor ID"))
        self.labelValueType.setText(_translate("MainWindow", "Value Type"))
        self.labelStart.setText(_translate("MainWindow", "Start"))
        self.labelEnd.setText(_translate("MainWindow", "End"))
        self.labelStepSize.setText(_translate("MainWindow", "Step Size"))
        self.pushButtonPlot.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sensor), _translate("MainWindow", "Sensor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_node), _translate("MainWindow", "Control Node"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
